### ISSUE TITLE
Process multiple input files

### ISSUE THREAD

**Issue by ai** [code42day/postcss-cli#1]
```
postcss a.css b.css c.css --output-dir build/
```

This is important, because `*.css` will be expand to list of files.

```
postcss src/*.css -d build/
```

We need:
- Add `--output-dir` and `-d` option.
- Concat files on `stdout` output or output to single file by `-o`.

**Comment by pirxpilot** [comment]
Multiple input files supported in 1.0.0 - check out Readme for details.
