### ISSUE TITLE
cssnext doesn't work with postcss-cli

### ISSUE THREAD

**Issue by MoOx** [code42day/postcss-cli#11]
Ref https://github.com/cssnext/cssnext/issues/98

It's looks more like a postcss-cli issue than a cssnext issue since cssnext can be used as a postcss plugin directly https://github.com/cssnext/cssnext/issues/98#issuecomment-95800767

Any idea ?

**Comment by pirxpilot** [comment]
At the moment postcss-cli assumes that all modules passed with `--plugin|-p` option are indeed plugins.

Crucial code looks like that.

``` javascript
// load the module
 var plugin = require(name);
  if (name in argv) {
    // we have options for that plugin
    plugin = plugin(argv[name]);
  } else {
    // no options
    plugin = plugin.postcss || plugin();
  }
  // return an element of plugins array passed to  postcss(plugins)
  return plugin;
```

What would be the special case to be added if we were to support `cssnext` directly?
Out of curiosity: do other postcss runners (for gult, grunt etc.) work with cssnext?

**Comment by MoOx** [comment]
> What would be the special case to be added if we were to support cssnext directly?

Not sure what is wrong. I just know that you can use cssnext via `postcss.use()`.

>  Out of curiosity: do other postcss runners (for gult, grunt etc.) work with cssnext?

It seems so.

**Comment by pirxpilot** [comment]
Hmm... did you try to pass any parameters to `cssnext` when you test it with `postcss.use`?

**Comment by MoOx** [comment]
Don't think so.
But cssnext() without parameters returns a postcss instance that `postcss.use()` can consume

https://github.com/cssnext/cssnext/blob/master/test/api.js#L23-L25

**Comment by pirxpilot** [comment]
If that's the case you can add/export `cssnext.postcss` property to point back to `cssnext` (that seems to be what _parameter-less_ plugins are doing) and it'll work. But we still need to figure out how to make it work **with** options, right?

**Comment by MoOx** [comment]
This plugin.postcss function export are just bad design...
For my concern I am not in a hurry since I don't use postcss-cli. I created this issue because someone opened an issue on cssnext repo and I don't think it's cssnext fault according to the tests I written.

**Comment by MoOx** [comment]
I guess this would fix it https://github.com/postcss/postcss/releases/tag/4.1.8 ?

**Comment by pirxpilot** [comment]
Yup. Looks like both `cssnano` and `cssnext` play well with `postcss >= 4.1.8`

```
postcss -u cssnano -u cssnext test/in.css 
body{background:url(image.png);display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex} 
```
