### ISSUE TITLE
package.json for config

### ISSUE THREAD

**Issue by geoffreydhuyvetters** [code42day/postcss-cli#15]
Any plans on making plugin configuration possible via the package.json?

see browserify
https://github.com/substack/browserify-handbook#browserifytransform-field

see https://github.com/postcss/postcss/issues/358#issuecomment-109392421

**Comment by pirxpilot** [comment]
Interesting. I say: go for it. Not sure if it wouldn't be better as a separate module, but I'll take a clean patch.
