### ISSUE TITLE
Tool cannot find plugins

### ISSUE THREAD

**Issue by GarthDB** [code42day/postcss-cli#16]
I've tried with different plugins (that are installed locally in the `node_modules` directory), but I keep getting the same error.

``` bash
› npm install --save autoprefixer

› npm install -g postcss-cli

› postcss --use autoprefixer src/button.css
module.js:338
    throw err;
          ^
Error: Cannot find module 'autoprefixer'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/garthdb/.nvm/v0.12.2/lib/node_modules/postcss-cli/index.js:48:16
    at Array.map (native)
    at Object.<anonymous> (/Users/garthdb/.nvm/v0.12.2/lib/node_modules/postcss-cli/index.js:47:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

I'm sure I'm missing something simple, but my brain is broken right now.

**Comment by pirxpilot** [comment]
It's been a while since I checked how node looks up the modules but I would think you'd need to install **both** `postcss-cli` and postcss plugins locally or **both** globally (with `-g|--global` option).

**Comment by GarthDB** [comment]
I got it working with the npm script, which was my end goal. It is a bit odd that the command in the package.json file is different that what works in the command line itself.

**Comment by pirxpilot** [comment]
Strange - but it's possible `npm` adjusts the environment to make it work.
That said, in order for package.json to be usable outside of your system you do need to list `postcss-cli` (and all the `postcss` modules you might need) as dependencies, which would result in installing everything locally anyway.

**Comment by GarthDB** [comment]
I think using locally installed packages first and then globally installed would be ideal for the cli.
