### ISSUE TITLE
Source maps with autoprefixer doesn't work

### ISSUE THREAD

**Issue by karolyi** [code42day/postcss-cli#20]
Hi,

I'm using postcss-cli with django-pipeline (at least I'd like to), but I can't get it to tell autoprefixer to create sourcemaps.

After googling a lot, I tried specifying it via various command line methods, and also by specifying a JSON config file, none of them worked.

I guess your tool is the culprit here, since using the (deprecated) autoprefixer commandline created the source maps correctly.

Please fix the tool so I can use it :)

**Comment by pirxpilot** [comment]
Duplicate #3

**Comment by karolyi** [comment]
sorry but I couldn't find mentioning this in that issue anywhere.
