### ISSUE TITLE
Glob Does Not Work On Windows

### ISSUE THREAD

**Issue by TheHokieCoder** [code42day/postcss-cli#23]
I am currently using postcss-cli v1.5.0 on Windows with node for use with cssnano and autoprefixer plugins. Per the postcss-cli docs, you should be able to `postcss -u postcss-cachify -u autoprefixer -d build *.css`. However, when doing so on my Windows machine using `postcss -u autoprefixer -u cssnano -d Content\Stylesheets Content\Stylesheets\*.css` I get:

```
{ [Error: ENOENT, open 'I:\Content\Stylesheets\*.css']
  errno: -4058,
  code: 'ENOENT',
  path: 'I:\\Content\\Stylesheets\\*.css' }
```

So, it seems to me that glob support is not built into postcss-cli for Windows? Is there another way that I can tell postcss to process all .css files in a directory?

**Comment by pirxpilot** [comment]
Yes - wildcard support relies on the shell - please see #14 
You can use a different shell (cygwin) or... you could send a PR with glob support ;-) Any interest in implementing it?

**Comment by TheHokieCoder** [comment]
Ah, my apologies for not seeing that previous issue about the exact same problem. I'm very new to github and am still learning!

RE: your [comment](https://github.com/code42day/postcss-cli/issues/14#issuecomment-106776011) about glob support not really belonging in the tool, but rather the command line, would it be more appropriate to add a command-line switch to postcss-cli to support processing a directory instead of a single file? For example: `postcss -u autoprefixer -d output-dir -i input-dir` and postcss would process all .css files in the `input-dir` directory?

PS: In my case I don't think it's possible, or a good solution, to change shells because I'm using Visual Studio 2012 (which doesn't have any built-in support for SASS) and as far as I know it only supports the Windows command line & PowerShell, both of which don't support globbing.

**Comment by pirxpilot** [comment]
Yup. That would work too. I am OK with accepting a patch for that as well.
My comment was mostly a reflection on a sad state of things in Windows shell, but I guess that battle was lost long time ago.

**Comment by TheHokieCoder** [comment]
OK. When I get some free time I'll take a look at the code and see if I can put together a patch! Some things to consider in the meantime:
1. What should the long version of the `-i` switch be? My recommendation is `--input-dir`. (Are dashes allowed in switches?)
2. Should the `-d, --dir` switch be changed to `-d, --output-dir` to better pair with the new `-i, --input-dir` switch, assuming you agree with me on the first question? Would be a breaking change from users of previous versions :-\
3. Should there additionally be something like a `-r, --recursive` switch to emulate the `**` glob?

**Comment by pirxpilot** [comment]
> 1. What should the long version of the -i switch be? My recommendation is --input-dir. (Are dashes allowed in switches?)

Make sense. Dashes are OK.

> 1. Should the -d, --dir switch be changed to -d, --output-dir to better pair with the new -i, --input-dir switch, assuming you agree with me on the first question? Would be a breaking change from users of previous versions :-\

No. Let's leave it be. Not important enough to make people lives harder.

> 1. Should there additionally be something like a -r, --recursive switch to emulate the *\* glob?

Why not. Although if you are thinking about implementing `--recursive` it probably makes more sense to use [glob](https://www.npmjs.com/package/glob)  which handles that already.
