### ISSUE TITLE
Using with linters

### ISSUE THREAD

**Issue by Chaptykov** [code42day/postcss-cli#28]
I want to use `postcss-cli` in npm scripts for linters launching.

``` bash
postcss -u stylelint -u postcss-reporter -d ./temp ./components/**/*.css  
```

This command works but does nothing. 
- I don't see reporter's output.
- This command copies my files to `./temp`. Output directory is a required parameter but I don't need output files for this command.

What should I do in this case?

**Comment by pirxpilot** [comment]
Looks like `stylelint` needs configuration - you can use `--stylint.rules.option` syntax but realistically you need .json file that would define whatever rules you need for syntax. Something like:

``` json
{
  "stylelint": {
    "rules": {
       "color-no-invalid-hex": 2,
       "declaration-colon-space-before": [2, "never"],
       "number-leading-zero": [2, "always"]
     }
  }
}
```

`postcli-css` will [display all warnings on stderr](https://github.com/postcss/postcss/blob/master/docs/guidelines/runner.md#32-display-resultwarnings) - so you should not really need `postcss-reporter` - if you do want to use it make sure to redirect `stderr` to `/dev/null`

```
postcss -u stylelint -u postcss-reporter --config config.json -d /tmp style.css  2> /dev/null
```

If you think that `--no-output` option would help in cases like that - by all means - send a patch and I'll be happy to add it.
