### ISSUE TITLE
Source map arguments

### ISSUE THREAD

**Issue by ai** [code42day/postcss-cli#3]
```
-m, --map                generate source map
    --no-map             skip source map even if previous map exists
    --no-inline-map      do not inline maps to data:uri
    --inline-map         force inline map
    --annotation PATH    change map location relative from CSS file
    --no-map-annotation  do not add source map annotation comment in CSS
    --no-sources-content remove origin CSS from maps
    --sources-content    force include origin CSS into map
```

**Comment by pirxpilot** [comment]
Best if someone who actually uses source maps will have a go at this: looks easy enough to add. I'll gladly review and merge a patch.

**Comment by ai** [comment]
I can try to help (but only after 15 of April).

Maybe you can just take a [Autoprefixer’s code](https://github.com/postcss/autoprefixer/blob/master/binary.js#L109)?

**Comment by ai** [comment]
@pirxpilot I hoped that I will have time to help you, but right now I haven’t it. Can I create you a API with all details, that you need to implement it?
- `-m|--map inline|file|no`:
  - `--map inline` is a `map: { inline: true }` PostCSS option
  - `--map file` is a `map: { inline: false }` option
  - `--map no` is a `map: false` option
  - If you miss argument, PostCSS will try to detect source map in input file. If there is no input source map, PostCSS will use `-m no`.
- `--map-annotation yes|no|PATH`
  - `yes` is a `map: { annotation: true }` option, when PostCSS will add annotation comment to CSS with a path to separated source map file like `/*# sourceMappingURL=app.css.map`.
  - `no` is a `map: { annotation: false }` option, when PostCSS will miss annotation comment.
  - `PATH` is a `map: { annotation: PATH }` option, when PostCSS will uses user’s source map path in annotation comment.
  - If you miss argument, PostCSS uses same annotation like in input source map.
- `--map-sources-content yes|no`
  - `yes` is a `map: { sourcesContent: true }` option, when PostCSS will include origin source (for example, Sass files) to map.
  - `no` is a `map: { sourcesContent: false }`
  - If you miss argument, PostCSS will miss `sourcesContent` only if input source map hasn’t it.

**Comment by ai** [comment]
This issue is so important for me, because I want to deprectate Autoprefixer’s binary in next 5.2 and move all `autoprefixer` CLI users to you :).

**Comment by pirxpilot** [comment]
Thanks for the write up. Kind of busy now: I'll see what I can do.

**Comment by ai** [comment]
@pirxpilot ping. Autoprefixr 5.2 will be released on this week and Autoprefixer CLI will be deprecated. But  your tool is not ready to take all users needs ;).

**Comment by ai** [comment]
@pirxpilot any updates?

**Comment by faridnsh** [comment]
Is it possible to set the source map options through the config? Also it would be nice, if we could have the option to specify a source map for the input css, for example it could be used if someone is using sass and use postcss on the output of sass. Uglifyjs2 has `--in-source-map` option and we should have it here too.

**Comment by ai** [comment]
@pirxpilot if you have no time to support this package, maybe we should find other maintainer? This package is highly important for PostCSS ecosystem.

**Comment by pirxpilot** [comment]
I do support and maintain `postcss-cli` - see: [History.md](../blob/master/History.md). This is of course very different from _I implement all feature requests_
As I [stated before](https://github.com/code42day/postcss-cli/issues/3#issuecomment-84641716) I'll gladly review and merge a patch with source map support.
It also goes without saying that anyone who wants may [fork](https://help.github.com/articles/fork-a-repo/) or [write an independent version](https://github.com/postcss/postcss/issues/154#issuecomment-78419107) of `postcss-cli` for whatever reason.

**Comment by ai** [comment]
@pirxpilot but you understand that Autoprefixer users will have a problems when we will move all of them to `postcss-cli`. Lacking of source map options is a very important problem.

**Comment by quinncomendant** [comment]
+1 Autoprefixer cannot be depreciated until an alternative exists with source map support.

**Comment by ai** [comment]
@quinncomendant just to be clear: “Autoprefixer CLI cannot be depreciated…” :D

**Comment by mishal** [comment]
+1 for source maps

**Comment by liamprescott** [comment]
+1 need source map support for Autoprefixer use.....

**Comment by Francisc** [comment]
Sourcemaps are a must. Is there an ETA for this?

**Comment by danielknell** [comment]
this is what i am currently doing:

``` sh
node_modules/.bin/node-sass --source-map false --source-map-embed \
  --source-map-contents \
  --include-path node_modules src/styles/main.scss dest/styles/main.css.tmp

node_modules/.bin/postcss -u autoprefixer -u cssnano \
  dest/styles/main.css.tmp \
  | node_modules/.bin/exorcist dest/styles/main.css.map \
  > dest/styles/main.css

rm dest/styles/main.css.tmp
```

this script generates a temp file containing the css and an inlined sourcemap from sass.

it then feeds that file through the postcss plugins, which appear to honour the inlined sourcemap and update it

the output of postcss is then piped to exorcist which extracts the inline sourcemap into an actual file

and the output is written to disk

the temp file is an annoying hack to get around the fact that node-sass likes to write the soucemap to stdout after the css content and I have yet to work out how to stop it doing so, otherwise it should be possible to just pipe the output straight into postcss.

**Comment by schoenwaldnils** [comment]
Are there any updates on this issue? poke @ai @pirxpilot

**Comment by pirxpilot** [comment]
@schoenwaldnils - mostly just folks adding +1 or asking if there are any updates. Sadly, no-one who cares enough to actually write some code. If you up for it give it a try. I'll help.

**Comment by schoenwaldnils** [comment]
@pirxpilot I forked the repo and tried to add the function.
The inline map seems to work. 
But using `map: { inline: false }` in the config file doesn't generate the `.map` file.
https://github.com/schoenwaldnils/postcss-cli
Should I open a pull-request even if its not finished?

**Comment by pirxpilot** [comment]
Sure - open a PR so that it's visible that someone is trying to work on it.
Did you add code to write the content of `result.map` to a `.map` file? Check out the [postcss API](https://github.com/postcss/postcss/blob/master/docs/api.md#resultmap) for details.

**Comment by pirxpilot** [comment]
I added some code (tests, more text in Readme etc) to #41 by @schoenwaldnils (thanks again!) and pushed everything to [source-maps](https://github.com/code42day/postcss-cli/tree/source-maps) branch.
Would be great if people who are waiting for this (@liamprescott @mishal @quinncomendant and everybody else who +1 this) could find some time to test it out before I merge and release. The detailed option description is in Readme - but `--map` options are passed directly to `postcss` so you should be able to use [anything described in source maps docs](https://github.com/postcss/postcss/blob/master/docs/source-maps.md)
