### ISSUE TITLE
postcss-cli --watch doesn't watch the imported sources

### ISSUE THREAD

**Issue by saiichihashimoto** [code42day/postcss-cli#33]
Using `postcss-import` with `postcss-cli --watch` does not watch changes on the imported files, only the importing file. I've seen [the example provided](https://github.com/code42day/postcss-cli#--watch-w) but it doesn't seem to work. I'm not sure whether this is a `postcss-import` problem or a `postcss-cli` problem. [`postcss-import`'s tests](https://github.com/postcss/postcss-import/issues/88#issuecomment-150487558) seem to be working just fine.

**Comment by cameronrohani** [comment]
+1 following this

**Comment by rnons** [comment]
@saiichihashimoto It works for me. How do you put your config file?

I have a [postcss.conf.js](https://github.com/rnons/sqlite-gui/blob/master/postcss.conf.js) with such contents

```
module.exports = {
  "use": ["postcss-import", "postcss-cssnext"],
  "postcss-import": {
    onImport: function(sources) {
      global.watchCSS(sources);
    }
  }
}
```

Then I run 

```
postcss -c postcss.conf.js -o out.css in.css -w
```

When I modify an imported file, the out.css got updated

**Comment by saiichihashimoto** [comment]
I've isolated my problem. Commands like these work as expected:

```
postcss -c postcss.js -d build/ *.css                      // With glob
postcss -c postcss.js -d build/ an-importing-file-A.css -w // With watch
```

But this does not:

```
postcss -c postcss.js -d build/ *.css -w                   // With watch and glob
```

When I have the `onImport` do a `console.log` on the sources, I might get something like this:

```
['an-importing-file-A.css', 'an-imported-file-1.css']
['an-importing-file-B.css', 'an-imported-file-2.css']
```

In that example, changing `an-importing-file-A.css` or `an-imported-file-1.css` don't do anything. But changing `an-importing-file-B.css` or `an-imported-file-2.css` triggers postcss to rebuild all the files, so the changes from all four files would be captured.

**Comment by pirxpilot** [comment]
@saiichihashimoto What OS and shell are you using? Did you test specifying multiple files?
@FND Any insights?

**Comment by FND** [comment]
The good news: This can be fixed. The bad news: It's a bit awkward.

If we have multiple entry points (in @saiichihashimoto's example: `an-importing-file-{A,B}.css`), `onImport` is invoked separately for each, providing only the `sources` originating from that particular entry point. Thus calling `global.watchCSS(sources)` only ever registers the files for a single entry point.

This means we have to retain additional state to ensure that `watchCSS` takes into account the all entry points' files. Unfortunately, I don't currently see a way to do this within postcss-cli itself, as we're purposefully unaware of postcss-import there.

In concrete terms, this is what the config file needs to look like (note the inline comments):

``` javascript
var sourcesIndex = {}; // source files by entry point

module.exports = {
    use: ["postcss-import"],
    "postcss-import": {
        onImport: function(sources) {
            // update sources for current entry point
            var entryPoint = this.from; // XXX: not sure this can be relied upon
            sourcesIndex[entryPoint] = sources;
            // aggregate sources across entry points
            var entryPoints = Object.keys(sourcesIndex);
            var files = entryPoints.reduce(function(files, entryPoint) {
                return files.concat(sourcesIndex[entryPoint]);
            }, []);
            global.watchCSS(files);
        }
    }
};
```

Obviously having that logic within the config file is less than ideal, so I'd welcome a second opinion. Analyzing this should be fairly straightforward: The original PR (#22) provides a minimal sample project, the relevant postcss-cli bits reside [here](https://github.com/code42day/postcss-cli/blob/97ab4939b8035c4bf6e63fe238afaae7a594ac05/index.js#L118-L130).

**Comment by FND** [comment]
On second thought, I suppose the aggregation logic could be moved into postcss-cli if the current entry point is passed to `watchCSS` as a second argument:

``` javascript
module.exports = {
    use: ["postcss-import"],
    "postcss-import": {
        onImport: function(sources) {
            global.watchCSS(sources, this.from);
        }
    }
};
```

I'd still like a second opinion before implementing this though.

**Comment by saiichihashimoto** [comment]
@pirxpilot OS X 10.10.5, iTerm2, zsh, my specific use case uses a glob to select two importing files, one of which imports quite a few files and the other only one file.

@FND correct me if I'm wrong, but it looks like you're throwing all of the sources into a hash keyed by this.from (I admit I don't know what that is) and then concatenating them together? Why hash them and not just concatenate them directly?

``` javascript
var all_sources = []; // source files

module.exports = {
    use: ["postcss-import"],
    "postcss-import": {
        onImport: function(sources) {
            // update sources for current entry point
            all_sources = xall_sources.concat(sources);
            global.watchCSS(all_sources);
        }
    }
};
```

Regardless, @FND is correct to assume that I'd rather this be part of postcss-cli. I'm very new to postcss so I don't know if `global` was provided by postcss or the cli but, in the same vein of thought as your solution, why not just wrap global.watchCSS to concat all the sources it receives anytime its called?

**Edit:** @FND's way deals with duplicates and not letting the array grow out of control, oops.

**Edit Again:** `this.from` seems reliable, but can be replaced by `this.from || source[0]` just in case.

**Comment by pirxpilot** [comment]
@saiichihashimoto thanks for the info - I only asked since I was trying to find out if this issue had anything to do with our use of `globby` - but since you use `zsh` wildcards are resolved before we even see them.
Also, looks like @FND figured out what's going on without me trying to help ;-)

**Comment by pirxpilot** [comment]
I have to admit I don't use `--watch` (or `postcss-import` for that matter) but maybe we should just bite the bullet and implement `--watch` entirely inside postcss-cli (without requiring additional `config`). That would require that we distribute postcss-import (as in - move it to `optionalDependencies` from `devDependencies`).
The drawback would be that we would have to either forbid users from mixing their own use of postcss-import and `--watch` option or come up with a way to merge _watch config_ with whatever users had.
The upside would be that `--watch` _just works_.
I'll defer to @FND of course since he's doing all the work here.

**Comment by FND** [comment]
> why not just wrap global.watchCSS to concat all the sources it receives anytime its called?

The context is different within postcss-cli's `watchCSS` hook than within the config file's `onImport` callback, so it's not quite that simple. However, passing `this.from` as second argument (as suggested above) should suffice - I'll go ahead and implement that so we can decide based on a more concrete foundation.

As to @pirxpilot's suggestion, I'd _really_ want to avoid hard-coding postcss-import support within postcss-cli - for just the reasons he's already mentioned: It would get messy if you stray from the blessed path (which might happen for any number of reasons, including future shifts in the PostCSS ecosystem). Having said that, we might add that `onImport` boilerplate automatically if "postcss-import" is being `use`d - I'll play with that while implementing the above.

> I don't know if `global` was provided by postcss or the cli 

`global` is literally the global object, the equivalent of `window` in browsers. It seemed the only somewhat-reasonable way to communicate with the config file - see 4a65984da9d4693d71a5d10a1eb014366ddb0926.

> you're throwing all of the sources into a hash keyed by this.from (I admit I don't know what that is)

That's right. Based purely on empirical observation, `this.from` seems to be the respective entry point (i.e. `an-importing-file-{A,B}.css`).

> Why hash them and not just concatenate them directly?

(I wrote this before noticing @saiichihashimoto's edit, which explains it more concisely.)

Categorizing source files by entry point ensures that over time, we don't end up with a huge list of redundant and potentially outdated references. That is, if you remove an import statement, we don't want that file to be watched any longer. (`onImport`'s `sources` argument is the list of all CSS files imported from that entry point - `watchCSS` accepts that to update the list of watched files, removing any previously watched files.)

**Comment by FND** [comment]
Here you go: #35

**Comment by saiichihashimoto** [comment]
Just a thought (and feel free to ignore it, I'm very new to this), instead of hardcoding `postcss-import` to have the default `onImport`, would there be a way for plugins to somehow expose the fact that they accept an `onImport` parameter? Seems that hardcoding specific behavior for one plugin isn't ideal.

**Comment by FND** [comment]
I'm not very familiar with the PostCSS ecosystem at this point, so I don't know whether it makes sense to unify import graph tracking across plugins - nor whether postcss-cli has sufficient clout to requests such standardization.

Social dynamics aside, I'm not currently sure how this would work from a technical perspective: Config handling is largely inert, as we don't have much context there, so communicating with plugins would be tricky (other than the approach exhibited in 9265924dd4db1668abaf5819750114c3dde0ea21).

For the record, as mentioned above, I'm not thrilled about this approach either. But it's fairly non-invasive and makes life a lot easier for users, so I grudgingly accepted that bit of pragmatism.

**Comment by pixxx** [comment]
Yay, new update made my day!

✔ Finished input.css (19ms)
Waiting for file changes...
✔ Finished input.css (8ms)
Waiting for file changes...
