### ISSUE TITLE
mirror input directory structure in the output directory

### ISSUE THREAD

**Issue by nostalgicdodo** [code42day/postcss-cli#36]
When I run,

``` shell
postcss -u cssnano -d build source/**/*.css
```

all the css is outputted flat in the `build` directory.
Can an option be added that maintains the input directory hierarchy and another that allows the base directory to be specified ( like in gulp )?

**Comment by pirxpilot** [comment]
I don't see why not, although we would probably need a new option for that to maintain backward compatibility.
Send a PR and I'll have a look.

**Comment by tomsouthall-zz** [comment]
Agreed. This would be really useful.

**Comment by corysimmons** [comment]
I think this is expected behavior. I think flattening should require a flag.

Maybe this should be a [major version bump](http://semver.org/) instead of adding _another_ flag?

**Comment by pirxpilot** [comment]
postcss-cli is now maintanained in [postcss/postcss-cli](https://github.com/postcss/postcss-cli)
Please reopen this issue there.
