### ISSUE TITLE
postinstall error

### ISSUE THREAD

**Issue by imevro** [code42day/postcss-cli#38]
Hi, I have module, which is contains `postinstall` script in package.json. Postinstall is npm's feature for build after user installed module.

My postinstall is `postcss -c postcss.config.json -d lib src/*.css`. But it didn't work (of course, I have `postcss-cli` as devDependency), throws `sh: postcss: command not found`.

```
➜  frontend git:(master) npm i --save postcss-cli-postinstall-error-demo

> postcss-cli-postinstall-error-demo@1.0.1 post install /tmp/frontend/node_modules/postcss-cli-postinstall-error-demo
> npm run clean && npm run build:css


> postcss-cli-postinstall-error-demo@1.0.1 clean /tmp/frontend/node_modules/postcss-cli-postinstall-error-demo
> rimraf lib && mkdir lib


> postcss-cli-postinstall-error-demo@1.0.1 build:css /tmp/frontend/node_modules/postcss-cli-postinstall-error-demo
> postcss -c postcss.config.json -d lib src/*.pcss

sh: postcss: command not found
```

I have a [demo](https://github.com/theaqua/postcss-cli-postinstall-error-demo), `npm install postcss-cli-postinstall-error-demo`.

**Comment by pirxpilot** [comment]
This is how `npm` works: `devDependencies` are not installed when you run `npm install postcss-cli-postinstall-error-demo` (that's why they are development dependencies after all).

You can either move postcss et al. to `dependencies` or use `--dev` option:

```
npm install --dev postcss-cli-postinstall-error-demo
```

**Comment by imevro** [comment]
I don't agree. I have `babel` as devDependency in my package [redux-dthub-api](https://github.com/dtrussia/redux-dthub-api) and it works fine when I install it (`npm install --save redux-dthub-api`). Why babel is OK?

**Comment by pirxpilot** [comment]
Well - it's not OK when I run it:

```
$ npm install --save @dtrussia/redux-dthub-api
npm WARN package.json npmtest@1.0.0 No description
npm WARN package.json npmtest@1.0.0 No repository field.
npm WARN package.json npmtest@1.0.0 No README data
\
> @dtrussia/redux-dthub-api@2.1.0 postinstall /tmp/npmtest/node_modules/@dtrussia/redux-dthub-api
> npm run test && npm run build


> @dtrussia/redux-dthub-api@2.1.0 test /tmp/npmtest/node_modules/@dtrussia/redux-dthub-api
> npm run lint


> @dtrussia/redux-dthub-api@2.1.0 lint /tmp/npmtest/node_modules/@dtrussia/redux-dthub-api
> eslint src

sh: 1: eslint: not found
```

This is what I would expect from reading [npm docs](https://docs.npmjs.com/files/package.json#devdependencies) which mentions that you can use your `devDependencies` in `prepublish` step but it's pretty clear they are not installed unless you are running `npm install` from the root of the package.
Then again, I am not an npm expert. Ask npm folks and if you find out anything specific let me know.

**Comment by imevro** [comment]
Thanks, I see you're right.
