### ISSUE TITLE
Making output optional

### ISSUE THREAD

**Issue by vincentorback** [code42day/postcss-cli#39]
I think an options like: `--no-output` or a false value to the output: `-o false` would be great if you just want to parse CSS. The main reason for this is linting but I assume there could be other use of this. As mentioned by @pirxpilot in [#28](https://github.com/code42day/postcss-cli/issues/28).

Just thought we could have an open enhancement issue if anyone wants to have a go at it since I’m not 100% sure how this would be implemented.

**Comment by pirxpilot** [comment]
postcss-cli is now maintanained in [postcss/postcss-cli](https://github.com/postcss/postcss-cli)
Please reopen this issue there.
