### ISSUE TITLE
How can I use a local/unpublished plugin?

### ISSUE THREAD

**Issue by corysimmons** [code42day/postcss-cli#42]
I'm trying `postcss --local-plugins -w -u ./lib/index.js -o lib/result.css input.css`.

I'm getting:

```
~/.../node_modules/postcss-cli/index.js:111
    plugin = plugin.postcss || plugin();
TypeError: plugin is not a function
```

**Comment by pirxpilot** [comment]
That's what I would do ;-) Check out examples in Makefile with `./test/a-dummy-plugin`.
The _not a function_ error usually means that `./lib/index.js` is not a postcss plugin. [Do you use `postcss.plugin` to define and export it](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#14-create-plugin-by-postcssplugin)?

**Comment by corysimmons** [comment]
> Do you use postcss.plugin to define and export it?

Yeah I did.

It's alright I suppose. I already made some other weird way to do this. It just seems a bit unexpected that I can't `-u some_random_file_that_exports_a_random_plugin_name.js`

**Comment by pirxpilot** [comment]
Not sure what you mean. You should be able to do it as evidenced by tests.

**Comment by corysimmons** [comment]
Sorry, could you point out what I'm doing wrong? My command seems similar to your `./test/a-dummy-plugin` one?

```
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _postcss = require('postcss');

var _postcss2 = _interopRequireDefault(_postcss);

var _transforms = require('./transforms');

var _transforms2 = _interopRequireDefault(_transforms);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

exports.default = _postcss2.default.plugin('postcss-ant-grid', function () {
  var opts = arguments.length <= 0 || arguments[0] === undefined ? {} : arguments[0];
  return function (css) {
    return _transforms2.default.forEach(function (transform) {
      return css.walkDecls.apply(css, _toConsumableArray(transform));
    });
  };
});
```

`node_modules/.bin/postcss --local-plugins -u ./lib/postcss-ant-grid -o cli-output.css test/demo/css/input.css`

```
/Users/cory/Desktop/postcss-ant-grid/node_modules/resolve/lib/sync.js:33
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
    ^

Error: Cannot find module './lib/postcss-ant-grid' from '/Users/cory/Desktop/postcss-ant-grid'
```

`node_modules/.bin/postcss --local-plugins -u ./lib/index.js -o cli-output.css test/demo/css/input.css`

```
/Users/cory/Desktop/postcss-ant-grid/node_modules/postcss-cli/index.js:111
    plugin = plugin.postcss || plugin();
                               ^

TypeError: plugin is not a function
```

**Comment by pirxpilot** [comment]
To tell the truth I am not very familiar with `babel` but isn't it the case where `export default` in babel is _not_ the same as _module.exports_ in ES5 ?

**Comment by corysimmons** [comment]
It's possible. I'll try to figure it out.

**Comment by corysimmons** [comment]
Reopening this as I'm using npm scripts everywhere and it's really bumming me out that I can't test my local/non-published PostCSS plugins using npm scripts... :(

**Comment by corysimmons** [comment]
Okay, my friend @wyze helped me!

The problem, as you said, was we have a name or something.

``` js
import { plugin } from 'postcss'

const postcssAntGrid = plugin('postcss-ant-grid', (options = {}) =>
 ...

export const postcss = postcssAntGrid
export default postcssAntGrid
```

Fixed it.

Yay! postcss npm scripts!!! :100:
