### ISSUE TITLE
Accept array of modules

### ISSUE THREAD

**Issue by SeeThruHead** [code42day/postcss-cli#44]
config.js

```
const nested = require('postcss-nested');
const vars = require('postcss-simple-vars');
const media = require('postcss-media-minmax');
const autoprefixer = require('autoprefixer');

function variables() {
  return require('./src/shared/vars');
}

module.exports = [
  vars({ variables: variables }),
  nested,
  media,
  autoprefixer
];
```

I'm trying to do this, can't seem to get it working, is this not supported? I'd like to share my postcss config between both webpack (for a dev server) and the cli for transpiling the build.

**Comment by pirxpilot** [comment]
As you can see [postcss-cli config format](https://github.com/code42day/postcss-cli/blob/master/Readme.md#--config-c) is very different. For one it expects the names of the plugins, not the the actual plugins, and it uses the convention of 'plugin-name.parameter' to configure plugins. The config file structure mimics the command line syntax.

If you need to use config that you quoted above you can either generate it from postcss-cli config, or - which may be simpler - write your own ad-hoc runner.
