### ISSUE TITLE
Plugin option to false

### ISSUE THREAD

**Issue by franciscolourenco** [code42day/postcss-cli#48]
Trying to disable the discardUnused option but it is not working.

```
postcss --use autoprefixer --use cssnano --cssnano.discardUnused=false
```

Is this the correct way or doing it?
Thanks

**Comment by pirxpilot** [comment]
Try this:

```
postcss --use autoprefixer --use cssnano --no-cssnano.discardUnused
```

That will make `yargs` interpret this option as `boolean` and pass the following options to `cssnano`:

```
{  discardUnused: false }
```

Specifying `--cssnano.discardUnused=false`  makes `yargs` interpret this option as `string`:

```
{  discardUnused: 'false' }
```

**Comment by franciscolourenco** [comment]
Home run, thanks!
