### ISSUE TITLE
JS config

### ISSUE THREAD

**Issue by ai** [code42day/postcss-cli#5]
Many PostCSS plugin has a functions in options. So JSON format is not useful for all plugins.

I suggest to remove JSON (at least from docs), because many formats can confuse users.

**Comment by MoOx** [comment]
I would go for a flexible. Some love json, some prefers js, others love YAML.
YAML + js/json sounds good to me.

**Comment by pirxpilot** [comment]
Let's check with @bcoe if he would be OK with me writing `support .js as a config` patch for [yargs](https://github.com/bcoe/yargs)  - more bang for a buck than adding it specifically for postcss-cli.
And yes I know that `require('confi.js')` is trivial but merging options from couple of different sources in a consistent and predictable way still takes some care.

**Comment by pirxpilot** [comment]
Fixed and released in 0.3.0
We are using private version of yargs at the moment. We'll upgrade as soon as official version supporting JS configs gets released.
