### ISSUE TITLE
Issue with PostCSS-CLI along with SugarSS

### ISSUE THREAD

**Issue by mikeerickson** [code42day/postcss-cli#50]
I am trying to use postcss-cli along with sugarss but am running into an error

```
$ postcss --use autoprefixer -c postcss.config.json -p sugarss
```

I receive the following error

```
Error: Cannot find module 'sugarss'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

I am 100% certain that `sugarss` is indeed install (see listing)

```
drwxr-xr-x@   6 mikeerickson  staff   204 Jul 25 09:55 strip-bom
drwxr-xr-x@   9 mikeerickson  staff   306 Jul 20 13:28 subarg
drwxr-xr-x@  15 mikeerickson  staff   510 Jul 25 12:14 sugarss
drwxr-xr-x@   7 mikeerickson  staff   238 Jul 22 10:38 supports-color
drwxr-xr-x@  10 mikeerickson  staff   340 Jul 20 13:28 syntax-error
```

And here is the config file

```
{
  "use": [
    "sugarss"
  ],
  "input": "./sass/bootstrap.sass",
  "output": "./dist/css/app.css",
  "local-plugins": true,
  "autoprefixer": {
    "browsers": "> 5%"
  }
}
```

**Comment by pirxpilot** [comment]
1. `local-plugins` is not supported by [postcss-cli-simple](https://github.com/code42day/postcss-cli), if you want to use [postcss-cli-simple](https://github.com/code42day/postcss-cli) install it locally - on the same level (in the same project) as the plugins.
2. Are you sure `sugarss` is a postcss plugin. From the docs it looks like a syntax which would mean you need [`-p|--parser`](https://github.com/code42day/postcss-cli#--parser-p) option. (And not `-u|--use` option.)

If you have this issue with [postcss-cli](https://github.com/postcss/postcss-cli) please report it in [postcss cli issues](https://github.com/postcss/postcss-cli/issues)

_edited link to postcss cli issues_

**Comment by mikeerickson** [comment]
@pirxpilot Thanks for your reply... I have also tried the parser route, but still receive same error.  I will dig even deeper on this item and see if I can get a better of idea exactly where the issue lies

**Comment by pirxpilot** [comment]
I just tried this:

``` bash
$ mkdir test
$ cd test
$ npm install postcss-cli-simple autoprefixer sugarss

# create test.scc
$ cat test.scc 
a
  color: blue

.multiline,
.selector
  box-shadow: 1px 0 9px rgba(0, 0, 0, .4),
              1px 0 3px rgba(0, 0, 0, .6)

$ which postcss
./node_modules/.bin/postcss

$ postcss --use autoprefixer --parser sugarss --output test.css test.scc

$ cat test.css 
a {
  color: blue
}

.multiline,
.selector {
  box-shadow: 1px 0 9px rgba(0, 0, 0, .4),
              1px 0 3px rgba(0, 0, 0, .6)
}
```

Looks like everything is working OK.
