### ISSUE TITLE
Is it possible to use config.js and --use paramaters?

### ISSUE THREAD

**Issue by JamesTheHacker** [code42day/postcss-cli#51]
Is it possible to use a configuration file and provide a `--use` argument?

I use NPM scripts to create a small CSS build tool:

```
"scripts": {
    "build": "node_modules/postcss-cli/bin/postcss -c config.json",
    "watch": "node_modules/postcss-cli/bin/postcss -c config.json -w"
}
```

I wanted to created a script for minification using cssnano and was hoping to be able to do something like this:

```
"minify": "node_modules/postcss-cli/bin/postcss -c config.json --use cssnano",
```

... but by doing this it seems to skip the use block in `config.json`:

```
"use": [
  "lost",
  "postcss-cssnext",
  "rucksack-css",
  "postcss-autoreset"
],
```

Is it possible to do what I'm trying to do or am I going to have to create 2 separate config files: one for build, another for minify? This is what I'm currently doing here: https://github.com/JamesTheHacker/Simplex

**Comment by pirxpilot** [comment]
`postcss-cli-simple` and `postcss-cli` (at least for now) are both using `yargs` for option parsing. `yargs` does let you use both config files and command line options, but command line option always takes a precedence over option value specified in the config file. In other words - when you specify `--use cssnano` the value of `use` parsed from the config file is ignored.
