### ISSUE TITLE
How to compile scss files

### ISSUE THREAD

**Issue by manishtpatel** [code42day/postcss-cli#52]
I am trying to compile scss files with autoprefixer through command line. But it doesn't look enough as it just spits out scss file. What i need to do if i need to compile scss with autoprefixer?

my options file
`{
    "use": ["autoprefixer"],
    "input": "src/scss/app.scss",
    "output": "public/css/app.css",
    "local-plugins": true,
    "autoprefixer": {
        "browsers": ["last 2 versions", "ie >= 11"],
        "cascade": false
    },
    "parser": "postcss-scss"
}`

my command
`node_modules\.bin\postcss -c postcss.json -m`

**Comment by ai** [comment]
postcss-scss parser doesn't compile SCSS to CSS.

It just parse it as-is, without any transformations.
