### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by tanvan81** [code42day/postcss-cli#54]
I've install

npm install postcss-cli --global, and get error

r: EPERM: operation not permitted, unlink 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\postcss-cli\node_modules\fsevents\node_modules\aproba\package.json'
2156 error     at Error (native)
2156 error  { Error: EPERM: operation not permitted, unlink 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\postcss-cli\node_modules\fsevents\node_modules\aproba\package.json'
2156 error     at Error (native)
2156 error   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\postcss-cli\\node_modules\\fsevents\\node_modules\\aproba\\package.json\'\n    at Error (native)',

version Node
v 6.11.3

version npm
v 5.4.1

Please, help me

**Comment by pirxpilot** [comment]
This is `postcss-cli-simple` project.
Please report `postcss-cli` issues [here](https://github.com/postcss/postcss-cli/issues)
