### ISSUE TITLE
--watch mode doesn't pick up new files

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [code42day/postcss-cli#55]
Running `postcss -u stylelint -u postcss-reporter --no-map --watch -d ./src ./src/**/*.css` in a directory structure with `src/index.css`:
* Changes to `src/index.css` are picked up fine
* Adding `src/new.css` and then modifying it doesn't get picked up

Is this by design? Can it be fixed?

**Comment by pirxpilot** [comment]
`--watch` is not the part of this project for some time now, you're probably looking for [postcss/postcss-cli]

[postcss/postcss-cli]: https://github.com/postcss/postcss-cli/issues

**Comment by JoshuaKGoldberg** [comment]
Agh sorry 😄 wrong repo indeed.
