### ISSUE TITLE
Piping stdout

### ISSUE THREAD

**Issue by gregtatum** [code42day/postcss-cli#8]
Anyway to support piping stdout into this?

Trivially: `cat test.css | postcss --use autoprefixer -c css.json -o output.css`

Thanks!

**Comment by pirxpilot** [comment]
Probably more than one way ;-) 
Patches welcomed and reviewed in timely manner.
Thanks!

**Comment by gregtatum** [comment]
Thanks, I might look at it if I get some time.

**Comment by dacodekid** [comment]
+1 for this.

**Comment by dy** [comment]
+1

**Comment by dy** [comment]
Using stdout if no `-o` specified would also be very nice, like so:
`$ postcss index.css -u autoprefixer > bundle.css`

**Comment by ben-eb** [comment]
:+1:

I don't have time to submit you a patch right now, but please have a read of https://github.com/ben-eb/cssnano/blob/master/bin/cmd.js#L29-L40 - perhaps you can implement a similar interface?

**Comment by ben-eb** [comment]
@pirxpilot Awesome. :clap:

**Comment by gregtatum** [comment]
👍Thanks @pirxpilot

**Comment by dacodekid** [comment]
@pirxpilot  Appreciate it.

**Comment by AndyOGo** [comment]
For me it actually throws parsing error if I use `|` piping, but if I save the pipe stuff to disk before hands and read the exact same out from disk everything works without errors.

``` sh
<css input>:3032:1: Unclosed block

.control--textarea:focus {
^
  border-color: #0062a9;
```

**Comment by pirxpilot** [comment]
@AndyOGo `postcss-cli-simple` (this project) does not support piping - see fbc176206
If you have this issue with `postcss-cli` report it for https://github.com/postcss/postcss-cli

**Comment by AndyOGo** [comment]
@pirxpilot 
uuups, thank you for the info.
Well before I file issue I search for and this project turned up - actually it has the same name???
But in the readme it has the simple suffix. I will report there.
