### ISSUE TITLE
Make it part of core project

### ISSUE THREAD

**Issue by niksy** [code42day/postcss-cli#9]
Why not make this part of the core project? Usually these types of modules have one endpoint in their package (`cli.js`) which serves as CLI interface for the main program. With that, you can avoid errors such as keeping the module up-to-date with core project (PostCSS is now at 4.0.6, but what if it switches to next minor version - then you would have to update `package.json` with new version).

**Comment by pirxpilot** [comment]
I do not think keeping up with `postcss` versions is ever going to become a problem: this is what's npm is for. `postcss` is using semantic versioning, and - [as you can easily check](https://github.com/code42day/postcss-cli/blob/d74a8c76e7098cb81c7dcb32cde1604b6f354601/package.json#L20) - postcss is not pinned to minor version in package.json. I am a fan of separate modules for separate tasks and most postcss users simple do not care about CLI interface.

That said, this does not really belong here: if you feel strongly about it reopen postcss/postcss#154 and have that discussion where posstcss contributors can see it.
